### ISSUE TITLE
Segment is not sending data to Google Analytics

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/redoc#90]
<img width="672" alt="screen shot 2018-01-19 at 3 32 29 pm" src="https://user-images.githubusercontent.com/3673236/35586099-b87eabd4-05ae-11e8-9a1c-1a0acc08da9d.png">

According to Google Analytics, there hasn't been data from docs.reactioncommerce.com since those 2 weeks in March 2016. We need Segment to send data to GA.

**Comment by jshimko** [comment]
I'm not sure what changed in Segment to cause this, but one thing I definitely know needed to be fixed was that the docs analytics were going the same place as `reactioncommerce.com` and there was no easy way to separate the data.  To remedy that and this issue here, I've created a new source in the Segment dashboard for the docs site.  We also need a new property in GA, but I don't currently have enough admin access to do that.  Once @aaronjudd (or whoever) adds a new property for `docs.reactioncommerce.com` in GA, I'll point the Segment source at it and we should be good to go.

**Comment by jshimko** [comment]
This has been fixed in #91

**Comment by jshimko** [comment]
This has been confirmed as resolved on the production site.
